name: Provision GCP Infrastructure

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}        
  GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }} 

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: 'read'
      id-token: 'write'
      
    steps:
      # Step 1: Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.0
  
      # Step 3: Authenticate to GCP
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
          
      # Step 4: Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Step 5: Validate Terraform configuration
      - name: Terraform Validate
        run: terraform validate

      # Step 6: Plan Terraform changes
      - name: Terraform Plan
        run: terraform plan -input=false -var="project_id=$PROJECT_ID" -var="gcp_credentials=$GCP_CREDENTIALS"

      # Step 7: Apply Terraform changes
      - name: Terraform Apply
        run: terraform apply -auto-approve -var="project_id=$PROJECT_ID" -var="gcp_credentials=$GCP_CREDENTIALS"
